root: true
env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - warn
    - args: none
  no-console: warn
  no-empty: warn
  no-useless-escape: off
  no-cond-assign: warn
  quotes:
    - error
    - backtick
  semi:
    - error
    - always
